services:
  app_react:
    build: .
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - eco-network
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

networks:
  eco-network:
    name: eco-network
    external: true

volumes:
  build_react:
