services:
  app_react:
    build: .
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react
    
networks:
  recyclable-backend_default:
    name: recyclable-backend_default
    external: true

volumes:
  build_react:
