on:
  push:
    branches:
      - main
name: Build and Deploy on AWS
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_REACT_APP_BACK_END_URL: ${{secrets.REACT_APP_BACK_END_URL}}
          envkey_REACT_APP_GOOGLE_API_KEY: ${{secrets.REACT_APP_GOOGLE_API_KEY}}
          envkey_REACT_APP_TOKEN_API_ULTRAMSG: ${{secrets.REACT_APP_TOKEN_API_ULTRAMSG}}
          envkey_REACT_APP_INSTANCE_API_ULTRAMSG: ${{secrets.REACT_APP_INSTANCE_API_ULTRAMSG}}
          directory: .
          file_name: .env
          fail_on_empty: true
      - name: Build
        run: docker compose build
      - name: Run
        run: docker compose down && docker compose up -d